/**
 * Theme System for Juda
 *
 * Provides the default theme with light/dark mode color definitions.
 * Users can override individual colors via customColors preference.
 * Preset themes are kept as starting points for customization.
 */

import { palette } from "./colors.js";

/**
 * All available themes (default + presets for customization starting points)
 */
export const themes = [
  {
    id: "default",
    name: "Default",
    colors: {
      light: {
        bgCanvas: palette.gray[50],
        bgSurface: "#FFFFFF",
        bgElevated: "#FFFFFF",
        iconPrimary: palette.blue[500],
        iconSecondary: palette.purple[500],
        iconAccent: palette.blue[600],
        buttonPrimary: palette.blue[600],
        buttonPrimaryHover: palette.blue[700],
        buttonPrimaryActive: palette.blue[800],
        primary: palette.blue[500],
        primaryHover: palette.blue[600],
        primaryActive: palette.blue[700],
        accent: palette.purple[500],
        accentHover: palette.purple[600],
        link: palette.blue[600],
        linkHover: palette.blue[700],
        focus: palette.blue[500],
        selection: palette.blue[50],
        selectionBorder: palette.blue[500],
        dndDropTarget: palette.blue[100],
        dndDropTargetBorder: palette.blue[400],
        calendarToday: palette.blue[500],
        calendarSelected: palette.blue[100],
      },
      dark: {
        bgCanvas: palette.gray[900],
        bgSurface: palette.gray[800],
        bgElevated: palette.gray[700],
        iconPrimary: palette.blue[400],
        iconSecondary: palette.purple[400],
        iconAccent: palette.blue[300],
        buttonPrimary: palette.blue[600],
        buttonPrimaryHover: palette.blue[500],
        buttonPrimaryActive: palette.blue[400],
        primary: palette.blue[400],
        primaryHover: palette.blue[300],
        primaryActive: palette.blue[200],
        accent: palette.purple[400],
        accentHover: palette.purple[300],
        link: palette.blue[400],
        linkHover: palette.blue[300],
        focus: palette.blue[400],
        selection: palette.blue[900],
        selectionBorder: palette.blue[400],
        dndDropTarget: palette.blue[900],
        dndDropTargetBorder: palette.blue[500],
        calendarToday: palette.blue[400],
        calendarSelected: palette.blue[800],
      },
    },
  },
  {
    id: "ocean",
    name: "Ocean",
    colors: {
      light: {
        bgCanvas: "#ecfeff",
        bgSurface: "#ffffff",
        bgElevated: "#f0fdfa",
        iconPrimary: "#0891b2",
        iconSecondary: "#0d9488",
        iconAccent: "#06b6d4",
        buttonPrimary: "#0e7490",
        buttonPrimaryHover: "#155e75",
        buttonPrimaryActive: "#164e63",
        primary: "#0891b2",
        primaryHover: "#0e7490",
        primaryActive: "#155e75",
        accent: "#0d9488",
        accentHover: "#0f766e",
        link: "#0891b2",
        linkHover: "#0e7490",
        focus: "#0891b2",
        selection: "#cffafe",
        selectionBorder: "#0891b2",
        dndDropTarget: "#a5f3fc",
        dndDropTargetBorder: "#22d3ee",
        calendarToday: "#0891b2",
        calendarSelected: "#cffafe",
      },
      dark: {
        bgCanvas: "#0a1419",
        bgSurface: "#0f1a1c",
        bgElevated: "#141f22",
        iconPrimary: "#22d3ee",
        iconSecondary: "#2dd4bf",
        iconAccent: "#67e8f9",
        buttonPrimary: "#0891b2",
        buttonPrimaryHover: "#06b6d4",
        buttonPrimaryActive: "#22d3ee",
        primary: "#22d3ee",
        primaryHover: "#67e8f9",
        primaryActive: "#a5f3fc",
        accent: "#2dd4bf",
        accentHover: "#5eead4",
        link: "#22d3ee",
        linkHover: "#67e8f9",
        focus: "#22d3ee",
        selection: "#164e63",
        selectionBorder: "#22d3ee",
        dndDropTarget: "#164e63",
        dndDropTargetBorder: "#06b6d4",
        calendarToday: "#22d3ee",
        calendarSelected: "#155e75",
      },
    },
  },
  {
    id: "forest",
    name: "Forest",
    colors: {
      light: {
        bgCanvas: "#f0fdf4",
        bgSurface: "#ffffff",
        bgElevated: "#ecfccb",
        iconPrimary: palette.green[600],
        iconSecondary: "#059669",
        iconAccent: "#84cc16",
        buttonPrimary: palette.green[700],
        buttonPrimaryHover: palette.green[800],
        buttonPrimaryActive: "#22543d",
        primary: palette.green[600],
        primaryHover: palette.green[700],
        primaryActive: palette.green[800],
        accent: "#059669",
        accentHover: "#047857",
        link: palette.green[600],
        linkHover: palette.green[700],
        focus: palette.green[600],
        selection: palette.green[50],
        selectionBorder: palette.green[600],
        dndDropTarget: palette.green[100],
        dndDropTargetBorder: palette.green[400],
        calendarToday: palette.green[600],
        calendarSelected: palette.green[100],
      },
      dark: {
        bgCanvas: "#0a1410",
        bgSurface: "#0f1a12",
        bgElevated: "#141f18",
        iconPrimary: palette.green[400],
        iconSecondary: "#10b981",
        iconAccent: "#a3e635",
        buttonPrimary: palette.green[600],
        buttonPrimaryHover: palette.green[500],
        buttonPrimaryActive: palette.green[400],
        primary: palette.green[400],
        primaryHover: palette.green[300],
        primaryActive: palette.green[200],
        accent: "#10b981",
        accentHover: "#34d399",
        link: palette.green[400],
        linkHover: palette.green[300],
        focus: palette.green[400],
        selection: palette.green[900],
        selectionBorder: palette.green[400],
        dndDropTarget: palette.green[900],
        dndDropTargetBorder: palette.green[500],
        calendarToday: palette.green[400],
        calendarSelected: palette.green[800],
      },
    },
  },
  {
    id: "sunset",
    name: "Sunset",
    colors: {
      light: {
        bgCanvas: "#fff7ed",
        bgSurface: "#ffffff",
        bgElevated: "#fef3c7",
        iconPrimary: palette.orange[500],
        iconSecondary: palette.red[500],
        iconAccent: "#f59e0b",
        buttonPrimary: palette.orange[600],
        buttonPrimaryHover: palette.orange[700],
        buttonPrimaryActive: "#9c4221",
        primary: palette.orange[500],
        primaryHover: palette.orange[600],
        primaryActive: palette.orange[700],
        accent: palette.red[500],
        accentHover: palette.red[600],
        link: palette.orange[600],
        linkHover: palette.orange[700],
        focus: palette.orange[500],
        selection: palette.orange[50],
        selectionBorder: palette.orange[500],
        dndDropTarget: palette.orange[100],
        dndDropTargetBorder: palette.orange[400],
        calendarToday: palette.orange[500],
        calendarSelected: palette.orange[100],
      },
      dark: {
        bgCanvas: "#14100a",
        bgSurface: "#1a140f",
        bgElevated: "#1f1814",
        iconPrimary: palette.orange[400],
        iconSecondary: palette.red[400],
        iconAccent: "#fbbf24",
        buttonPrimary: palette.orange[600],
        buttonPrimaryHover: palette.orange[500],
        buttonPrimaryActive: palette.orange[400],
        primary: palette.orange[400],
        primaryHover: palette.orange[300],
        primaryActive: palette.orange[200],
        accent: palette.red[400],
        accentHover: palette.red[300],
        link: palette.orange[400],
        linkHover: palette.orange[300],
        focus: palette.orange[400],
        selection: palette.orange[900],
        selectionBorder: palette.orange[400],
        dndDropTarget: palette.orange[900],
        dndDropTargetBorder: palette.orange[500],
        calendarToday: palette.orange[400],
        calendarSelected: palette.orange[800],
      },
    },
  },
  {
    id: "lavender",
    name: "Lavender",
    colors: {
      light: {
        bgCanvas: "#faf5ff",
        bgSurface: "#ffffff",
        bgElevated: "#fdf4ff",
        iconPrimary: palette.purple[500],
        iconSecondary: "#a855f7",
        iconAccent: "#d946ef",
        buttonPrimary: palette.purple[600],
        buttonPrimaryHover: palette.purple[700],
        buttonPrimaryActive: "#553C9A",
        primary: palette.purple[500],
        primaryHover: palette.purple[600],
        primaryActive: palette.purple[700],
        accent: "#a855f7",
        accentHover: "#9333ea",
        link: palette.purple[600],
        linkHover: palette.purple[700],
        focus: palette.purple[500],
        selection: palette.purple[50],
        selectionBorder: palette.purple[500],
        dndDropTarget: palette.purple[100],
        dndDropTargetBorder: palette.purple[400],
        calendarToday: palette.purple[500],
        calendarSelected: palette.purple[100],
      },
      dark: {
        bgCanvas: "#0f0a14",
        bgSurface: "#140f1a",
        bgElevated: "#18141f",
        iconPrimary: palette.purple[400],
        iconSecondary: "#c084fc",
        iconAccent: "#e879f9",
        buttonPrimary: palette.purple[600],
        buttonPrimaryHover: palette.purple[500],
        buttonPrimaryActive: palette.purple[400],
        primary: palette.purple[400],
        primaryHover: palette.purple[300],
        primaryActive: palette.purple[200],
        accent: "#c084fc",
        accentHover: "#d946ef",
        link: palette.purple[400],
        linkHover: palette.purple[300],
        focus: palette.purple[400],
        selection: palette.purple[900],
        selectionBorder: palette.purple[400],
        dndDropTarget: palette.purple[900],
        dndDropTargetBorder: palette.purple[500],
        calendarToday: palette.purple[400],
        calendarSelected: palette.purple[800],
      },
    },
  },
  {
    id: "slate",
    name: "Slate",
    colors: {
      light: {
        bgCanvas: palette.gray[50],
        bgSurface: "#ffffff",
        bgElevated: palette.gray[100],
        iconPrimary: palette.gray[600],
        iconSecondary: palette.gray[500],
        iconAccent: palette.gray[700],
        buttonPrimary: palette.gray[700],
        buttonPrimaryHover: palette.gray[800],
        buttonPrimaryActive: palette.gray[900],
        primary: palette.gray[600],
        primaryHover: palette.gray[700],
        primaryActive: palette.gray[800],
        accent: palette.gray[500],
        accentHover: palette.gray[600],
        link: palette.gray[700],
        linkHover: palette.gray[800],
        focus: palette.gray[600],
        selection: palette.gray[100],
        selectionBorder: palette.gray[600],
        dndDropTarget: palette.gray[200],
        dndDropTargetBorder: palette.gray[400],
        calendarToday: palette.gray[600],
        calendarSelected: palette.gray[200],
      },
      dark: {
        bgCanvas: palette.gray[900],
        bgSurface: palette.gray[800],
        bgElevated: palette.gray[700],
        iconPrimary: palette.gray[400],
        iconSecondary: palette.gray[300],
        iconAccent: palette.gray[500],
        buttonPrimary: palette.gray[600],
        buttonPrimaryHover: palette.gray[500],
        buttonPrimaryActive: palette.gray[400],
        primary: palette.gray[400],
        primaryHover: palette.gray[300],
        primaryActive: palette.gray[200],
        accent: palette.gray[500],
        accentHover: palette.gray[400],
        link: palette.gray[400],
        linkHover: palette.gray[300],
        focus: palette.gray[400],
        selection: palette.gray[700],
        selectionBorder: palette.gray[400],
        dndDropTarget: palette.gray[700],
        dndDropTargetBorder: palette.gray[500],
        calendarToday: palette.gray[400],
        calendarSelected: palette.gray[600],
      },
    },
  },
];

/**
 * Get theme by ID
 */
export function getThemeById(id) {
  return themes.find(t => t.id === id) || themes[0];
}

/**
 * Get all available themes
 */
export function getAllThemes() {
  return themes;
}
